CREATE TABLE IF NOT EXISTS institutional_holdings (
    id integer PRIMARY KEY,
    tick text NOT NULL,
    institutional_ownership_perc REAL,
    total_shares_outstanding_millions INTEGER,
    total_value_holdings_millions INTEGER,
    increased_positions_holders INTEGER,
    increased_positions_shares INTEGER,
    decreased_positions_holders INTEGER,
    decreased_positions_shares INTEGER,
    held_positions_holders INTEGER,
    held_positions_shares INTEGER,
    total_institutional_holders INTEGER,
    total_institutional_shares INTEGER,
    new_positions_holders INTEGER,
    new_positions_shares INTEGER,
    sold_out_positions_holders INTEGER,
    sold_out_positions_shares INTEGER,
    refreshed_page_date TIMESTAMP DEFAULT NULL,
    inserted TIMESTAMP DEFAULT (strftime('%d-%m-%Y %H:%M:%S', 'now')),
    FOREIGN KEY (tick) REFERENCES fk_institutional_holdings_tickers (tick))